# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'settingsaXXZps.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import rc

class Ui_Settings(object):
    def setupUi(self, Settings):
        if not Settings.objectName():
            Settings.setObjectName(u"Settings")
        Settings.resize(460, 265)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setMinimumSize(QSize(460, 265))
        Settings.setMaximumSize(QSize(460, 2655))
        Settings.setBaseSize(QSize(460, 265))
        icon = QIcon()
        icon.addFile(u":/files/img/configure.png", QSize(), QIcon.Normal, QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setAutoFillBackground(False)
        Settings.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        Settings.setModal(True)
        self.Base1 = QGroupBox(Settings)
        self.Base1.setObjectName(u"Base1")
        self.Base1.setGeometry(QRect(10, 9, 441, 111))
        self.path10 = QLineEdit(self.Base1)
        self.path10.setObjectName(u"path10")
        self.path10.setGeometry(QRect(80, 30, 311, 21))
        self.path11 = QLineEdit(self.Base1)
        self.path11.setObjectName(u"path11")
        self.path11.setGeometry(QRect(80, 60, 311, 21))
        self.label = QLabel(self.Base1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 61, 21))
        self.label_2 = QLabel(self.Base1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 60, 47, 16))
        self.sel10 = QToolButton(self.Base1)
        self.sel10.setObjectName(u"sel10")
        self.sel10.setGeometry(QRect(390, 30, 21, 21))
        icon1 = QIcon()
        icon1.addFile(u":/files/img/open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.sel10.setIcon(icon1)
        self.sel11 = QToolButton(self.Base1)
        self.sel11.setObjectName(u"sel11")
        self.sel11.setGeometry(QRect(390, 60, 21, 21))
        self.sel11.setIcon(icon1)
        self.conv1 = QToolButton(self.Base1)
        self.conv1.setObjectName(u"conv1")
        self.conv1.setGeometry(QRect(410, 30, 21, 21))
        self.conv1.setIcon(icon)
        self.cbHideDel = QCheckBox(self.Base1)
        self.cbHideDel.setObjectName(u"cbHideDel")
        self.cbHideDel.setGeometry(QRect(80, 90, 151, 17))
        
        self.Base2 = QGroupBox(Settings)
        self.Base2.setObjectName(u"Base2")
        self.Base2.setGeometry(QRect(10, 130, 441, 91))
        self.path20 = QLineEdit(self.Base2)
        self.path20.setObjectName(u"path20")
        self.path20.setGeometry(QRect(80, 30, 311, 21))
        self.path21 = QLineEdit(self.Base2)
        self.path21.setObjectName(u"path21")
        self.path21.setGeometry(QRect(80, 60, 311, 21))
        self.label_3 = QLabel(self.Base2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 61, 21))
        self.label_4 = QLabel(self.Base2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 60, 51, 16))
        self.sel20 = QToolButton(self.Base2)
        self.sel20.setObjectName(u"sel20")
        self.sel20.setGeometry(QRect(390, 30, 21, 21))
        self.sel20.setIcon(icon1)
        self.sel21 = QToolButton(self.Base2)
        self.sel21.setObjectName(u"sel21")
        self.sel21.setGeometry(QRect(390, 60, 21, 21))
        self.sel21.setIcon(icon1)
        self.conv2 = QToolButton(self.Base2)
        self.conv2.setObjectName(u"conv2")
        self.conv2.setGeometry(QRect(410, 30, 21, 21))
        self.conv2.setIcon(icon)

        self.bSave = QPushButton(Settings)
        self.bSave.setObjectName(u"bSave")
        self.bSave.setGeometry(QRect(290, 230, 80, 23))
        self.bCancel = QPushButton(Settings)
        self.bCancel.setObjectName(u"bCancel")
        self.bCancel.setGeometry(QRect(370, 230, 80, 23))

        self.retranslateUi(Settings)
        self.bCancel.clicked.connect(Settings.reject)

        QMetaObject.connectSlotsByName(Settings)
    # setupUi

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QCoreApplication.translate("Settings", u"Настройки программы", None))
        self.Base1.setTitle(QCoreApplication.translate("Settings", u"1. Infotor-2", None))
        self.label.setText(QCoreApplication.translate("Settings", u"Основная", None))
        self.label_2.setText(QCoreApplication.translate("Settings", u"Контент", None))
#if QT_CONFIG(tooltip)
        self.sel10.setToolTip(QCoreApplication.translate("Settings", u"Выберите файл БД", None))
#endif // QT_CONFIG(tooltip)
        self.sel10.setText("")
#if QT_CONFIG(tooltip)
        self.sel11.setToolTip(QCoreApplication.translate("Settings", u"Выберите файл БД", None))
#endif // QT_CONFIG(tooltip)
        self.sel11.setText("")
#if QT_CONFIG(tooltip)
        self.conv1.setToolTip(QCoreApplication.translate("Settings", u"Преобразовать в нужный формат", None))
#endif // QT_CONFIG(tooltip)
        self.conv1.setText("")
        self.cbHideDel.setText(QCoreApplication.translate("Settings", u"Скрывать удаленные", None))
        self.Base2.setTitle(QCoreApplication.translate("Settings", u"2. \"База данных с комментариями\"", None))
        self.label_3.setText(QCoreApplication.translate("Settings", u"Основная", None))
        self.label_4.setText(QCoreApplication.translate("Settings", u"Контент", None))
#if QT_CONFIG(tooltip)
        self.sel20.setToolTip(QCoreApplication.translate("Settings", u"Выберите файл БД", None))
#endif // QT_CONFIG(tooltip)
        self.sel20.setText("")
#if QT_CONFIG(tooltip)
        self.sel21.setToolTip(QCoreApplication.translate("Settings", u"Выберите файл БД", None))
#endif // QT_CONFIG(tooltip)
        self.sel21.setText("")
#if QT_CONFIG(tooltip)
        self.conv2.setToolTip(QCoreApplication.translate("Settings", u"Преобразовать в нужный формат", None))
#endif // QT_CONFIG(tooltip)
        self.conv2.setText("")
        self.bSave.setText(QCoreApplication.translate("Settings", u"Сохранить", None))
        self.bCancel.setText(QCoreApplication.translate("Settings", u"Отмена", None))
    # retranslateUi
